fixed example with not annotated target word
akutuzov/rushifteval_public pull request #2
Opened 2021-03-16 20:13 UTC by Vitaly-Protasov

2021-03-16 21:49 UTC, Vitaly-Protasov commented
Finally, @akutuzov, you can check changes:)

2021-03-17 13:42 UTC, akutuzov commented on raw_annotations/rusemshift1_raw_annotations.tsv
> +35	амбиция	Хоть с генеральскими детьми поводиться, так и тем на ногу себе наступить не позволит, потому я первым делом наблюдаю, чтобы в моих детях эта благородная <b><i>амбиция</i></b> была; как сам
Why a seemingly random piece of text is added here?

2021-03-17 13:42 UTC, akutuzov requested changes

2021-03-17 13:42 UTC, akutuzov commented on raw_annotations/rusemshift1_raw_annotations.tsv
> +35	амбиция	Хоть с генеральскими детьми поводиться, так и тем на ногу себе наступить не позволит, потому я первым делом наблюдаю, чтобы в моих детях эта благородная <b><i>амбиция</i></b> была; как сам
Can you fix this and make sure this does not happen elsewhere?

2021-03-17 16:13 UTC, Vitaly-Protasov commented
@akutuzov  Fixed.

2021-03-17 22:59 UTC, akutuzov approved these changes
Thanks a lot for your help!

2021-03-17 23:00 UTC, merged